#!/bin/bash

version_tag=${VERSION:-latest}
spt_release_version=${SPT_VERSION:-4.0.11-40087-278e72b
fika_version=${FIKA_VERSION:-2.2.0}
build_type=${BUILD_TYPE:-release}

docker build . \
    --build-arg BUILD_TYPE=$build_type \
    --build-arg SPT_VERSION=$spt_release_version \
    --build-arg FIKA_VERSION=$fika_version \
    -t fika-spt-server-docker:$version_tag $@
