#!/bin/bash

version_tag=${VERSION:-latest}
spt_sha=${SPT_SHA:-3.11.4}
fika_version=${FIKA_VERSION:-v2.4.8}
build_type=${BUILD_TYPE:-release}

docker build . \
    --build-arg BUILD_TYPE=$build_type \
    --build-arg SPT_SERVER_SHA=$spt_sha \
    --build-arg FIKA_VERSION=$fika_version \
    -t fika-spt-server-docker:$version_tag $@
